### PR TITLE
Fixes #501

### LINKED ISSUE #501: Earmark crashes (like EarmarkParser) on `"\\[{:}" `
https://github.com/RobertDober/earmark_parser/issues/154

here is the crash in Earmark master

```
Generated earmark app
Interactive Elixir (1.17.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> EarmarkParser.as_ast("\\[{:}")
** (UndefinedFunctionError) function EarmarkParser.as_ast/1 is undefined (module EarmarkParser is not available)
    EarmarkParser.as_ast("\\[{:}")
    iex:1: (file)
iex(1)> Earmark.as_ast("\\[{:}")
** (FunctionClauseError) no function clause matching in Earmark.Parser.Helpers.AstHelpers.augment_tag_with_ial/2

    The following arguments were given to Earmark.Parser.Helpers.AstHelpers.augment_tag_with_ial/2:

        # 1
        ["["]

        # 2
        %{}

    Attempted function clauses (showing 2 out of 2):

        def augment_tag_with_ial([{t, a, c, m} | tags], atts)
        def augment_tag_with_ial([], _atts)

    (earmark 1.4.46) lib/earmark_parser/helpers/ast_helpers.ex:33: Earmark.Parser.Helpers.AstHelpers.augment_tag_with_ial/2
    (earmark 1.4.46) lib/earmark_parser/ast/inline.ex:258: Earmark.Parser.Ast.Inline.converter_for_inline_ial/1
    (elixir 1.17.1) lib/enum.ex:4343: Enum.find_value_list/3
    (earmark 1.4.46) lib/earmark_parser/ast/inline.ex:36: Earmark.Parser.Ast.Inline._convert/4
    (earmark 1.4.46) lib/earmark_parser/ast_renderer.ex:32: Earmark.Parser.AstRenderer.render_block/3
    (earmark 1.4.46) lib/earmark_parser/ast_renderer.ex:23: Earmark.Parser.AstRenderer._render/3
    (earmark 1.4.46) lib/earmark_parser.ex:594: Earmark.Parser.as_ast/2
    iex:1: (file)
```

@amit-chaudhari1 if ok with you I (ab)use me right to assign it to myself as the liklhood that I can backport the fix is high

### PR DESCRIPTION
**Pull request by RobertDober**
A little bit of a clumsy solution but I could not come up with something better w/o a **major** refact.

### CODE REVIEW

File: lib/earmark_parser/ast/inline.ex [hunk 1]
```diff
@@ -255,7 +255,7 @@ defmodule Earmark.Parser.Ast.Inline do
     if match = Regex.run(@inline_ial, src) do
       [match, ial] = match
       {context1, ial_attrs} = parse_attrs(context, ial, lnb)
-      new_tags = augment_tag_with_ial(context.value, ial_attrs)
+      new_tags = augment_tag_with_ial(context.value, ial_attrs, match)
```
Comment (RobertDober) [inline lib/earmark_parser/ast/inline.ex:258]: Instead of taking track of the fact that we had just escaped a string I prepare for a fallback solution in the `augment_tag_with_ial` function

File: lib/earmark_parser/helpers/ast_helpers.ex [hunk 2]
```diff
@@ -28,15 +28,16 @@ defmodule Earmark.Parser.Helpers.AstHelpers do
...
+  def augment_tag_with_ial([{t, a, c, m}|tags], atts, _src) do
+    [{t, merge_attrs(a, atts), c, m}|tags]
   end
-
-  def augment_tag_with_ial([], _atts) do
+  def augment_tag_with_ial([], _atts, _src) do
     []
   end
+  def augment_tag_with_ial([any], _atts, src) do
+    [any <> src]
```
Comment (RobertDober) [inline lib/earmark_parser/helpers/ast_helpers.ex:39]: and here I use the fallback, we do not have an element, therefore we have escaped text and just append the unparsed IAL string again

**Comment by dominicletz** [comment]
@amit-chaudhari1 what do you think of this solution? Would love to be able to get a new release with this bugfix :heart:

**Review by amit-chaudhari1 — APPROVED** [review]

**Comment by amit-chaudhari1** [comment]
I will need @RobertDober 's help on creating a release.

**Comment by RobertDober** [comment]
I'll gladly do the release @amit-chaudhari1 

Do you have release rights on hex.pm already? Would you like help with other things?

Also would you like me to keep annoncing Releases on the Elixir Forum?

**Comment by amit-chaudhari1** [comment]
> Also would you like me to keep annoncing Releases on the Elixir Forum?

Yes please, for a while. 

> Do you have release rights on hex.pm already? Would you like help with other things?

No, I've registered on hex.pm but I don't think I can create the releases for earmark yet.
https://hex.pm/users/amyth

**Comment by RobertDober** [comment]
@amit-chaudhari1 should be ok now
```
 mix hex.owner add --level maintainer earmark amyth                                                                                                               Local password:
Adding owner amyth with ownership level maintainer to earmark
```
